apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: priyasingh1/udagram-api-user:v4
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-secret
