version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-push:
    executor: docker-executor
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build and Push Feed
          command: |
            docker build -t priyasingh1/udagram-api-feed:v4 ./udagram-api-feed
            docker push priyasingh1/udagram-api-feed:v4

      - run:
          name: Build and Push User
          command: |
            docker build -t priyasingh1/udagram-api-user:v4 ./udagram-api-user
            docker push priyasingh1/udagram-api-user:v4

      - run:
          name: Build and Push Frontend
          command: |
            docker build -t priyasingh1/udagram-frontend:v4 ./udagram-frontend
            docker push priyasingh1/udagram-frontend:v4

      - run:
          name: Build and Push Reverseproxy
          command: |
            docker build -t priyasingh1/reverseproxy:v4 ./udagram-reverseproxy
            docker push priyasingh1/reverseproxy:v4

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
